services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../:/web/mclogs
      - ./mclogs.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
      - redis

  php-fpm:
    build:
      dockerfile_inline: |
        FROM php:8.1-fpm
        COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
        RUN install-php-extensions mongodb redis
        COPY mclogs.ini /usr/local/etc/php/conf.d/mclogs.ini
    volumes:
      - ../:/web/mclogs
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    volumes:
      - mongo:/data/db

  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data

volumes:
  mongo:
  redis: